src/analytics/analytics/apps/core/urls.py
from django.conf.urls import url

from .views import HomePageView


urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),
]

src/analytics/analytics/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'', include('core.urls', namespace='core')),
    url(r'^admin/', include(admin.site.urls)),
]

src/analytics/analytics/apps/core/models.py
from django.db import models


class Provider(models.Model):
    """
    Represents Spiders/Data Providers
    """

    class Meta:
        verbose_name = "Provider"
        verbose_name_plural = "Providers"

    name = models.CharField(max_length=25)
    enabled = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def __repr__(self):
        return '<Provider {0}>'.format(self.name)


class Category(models.Model):
    """
    Represents static category for provider
    """

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    provider = models.ForeignKey(Provider)
    parent_category = models.ForeignKey('self')
    name = models.CharField(max_length=255)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

    def __repr__(self):
        return '<Category {0} {1}>'.format(self.provider.name, self.name)

src/analytics/analytics/apps/core/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = 'core/home.html'

src/analytics/analytics/apps/core/templates/core/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock title %}

{% block content %}

    <h1>Hello World</h1>

{% endblock content %}

src/analytics/analytics/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Analytics{% endblock title %}</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/core.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="">Analytics</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'core:home' %}">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">

        <div class="core-template">
            {% block content %}
            {% endblock content %}
        </div>

    </div><!-- /.container -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.inputmask.bundle.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>